version: '3'
services:

  postgres:
    container_name: project_postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5430:5432'

  cache:
    container_name: project_redis
    image: redis:6
    env_file:
      - .env
    ports:
      - "6380:6379"

  redisinsight:
    container_name: project_redisinsight
    image: redislabs/redisinsight
    ports:
      - "8001:8001"

  node_app:
    container_name: project_node
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
      - cache


